---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/git-commit: "f885b36e97e07e61ffcd687481506e210f963a6c"
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/git-branch: "master"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "fis-spring-boot"
    version: "1.0-SNAPSHOT"
    group: "com.apria.fis"
  name: "fis-spring-boot"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "fis-spring-boot"
    provider: "fabric8"
    group: "com.apria.fis"
