---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "fis-spring-boot"
  spec:
    tags:
    - from:
        kind: "ImageStreamImage"
        name: "fis-spring-boot@sha256:82091e1ff82e8c51d0018a74d3ab16189d8fc412592041746f0c5fefdb9a3d41"
        namespace: "fis"
      name: "latest"
